apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-grader-configmap
data:
  redis_host: {{.Values.env.redis_host}}
  llm_success_score_threshold: {{.Values.env.llm_success_score_threshold}}
  llm_fail_score_threshold: {{.Values.env.llm_fail_score_threshold}}