apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-grader.fullname" . }}
  labels:
    {{- include "llm-grader.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/api/v1/metrics'
    prometheus.io/port: '8000'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llm-grader.selectorLabels" . | nindent 4 }}
